volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static

  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    build: ./gateway/
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles
    ports:
      - "8000:80"
